### ISSUE TITLE
fta-cli npm package does not currently export type defs

### ISSUE THREAD

**Issue by sgb-io** [sgb-io/fta#26]

**Comment by EcoFreshKase** [comment]
Hi, I'm looking into creating the type declarations for the npm package.
How should the type declarations be implemented? Should a Pull Request be made on the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project, or should the declarations be added directly to the project?

I think it would make more sense to add them directly to the project. As far as I know, [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) ensures that types are well-commented. However, maintaining them there would be more of a hassle, as every interface change would require a new PR on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). That said, I don't expect frequent changes.

I've already created the type declarations (comments are still missing): [fta](https://github.com/EcoFreshKase/fta).

**Comment by sgb-io** [comment]
@EcoFreshKase thanks for the contribution!

Yes, it's best if the types are simply added direct to the project. You can open a PR with your changes and i'll adopt it.

I don't have major changes planned so the types are likely to remain stable, but it still makes sense to have the types co-located.

There is one caveat; I need to upgrade the github actions in order to get green builds and be able to release as there is currently a dependency on v2 actions that have recently been removed (see https://github.com/sgb-io/fta/issues/163)

**Comment by sgb-io** [comment]
The issue mentioned in #163 with the possible exception of some actions I depend on in release.yml (https://github.com/sgb-io/fta/blob/main/.github/workflows/release.yml). You should be good to submit a PR and I can merge it, then see if the release succeeds (or migrate the release actions as needed).

**Comment by sgb-io** [comment]
@EcoFreshKase I have now upgraded most of the workflow dependencies so the project can build and release successfully again.
I've just released 2.0.1 which includes your changes.
