### ISSUE TITLE
`GLIBC_2.29' not found when running on gitlab-ci

### ISSUE THREAD

**Issue by xquelard** [sgb-io/fta#41]
Hi there!

I'm having issues when running this project in a gitlab ci/cd environment. The following error is thrown when I try to use fta-cli : 

```/builds/pitchy-team/core/core-apps/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by xxxxxxx/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta)
/builds/pitchy-team/core/core-apps/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by xxxxxxx/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta)
Error: Command failed: xxxxxxx/core/core-apps/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta src --json
xxxxxxx/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by xxxxxxx/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta)
xxxxxxx/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by xxxxxxx/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta)```

As far as I'm concerned, I don't think there's anything special or out of the ordinary in my usage of the lib, but obviously, If you need additional information I'd be happy top help !

Thanks a lot

**Comment by sgb-io** [comment]
Thanks! I am hoping that will be fixed by switching over to linux musl as the binary target instead of gnu (https://github.com/sgb-io/fta/pull/43). I'll give this a test on the Gitlab runner when it's ready and report back

**Comment by sgb-io** [comment]
Hi @xquelard, this should be fixed now. I've tested using a Gitlab runner on the same image. Thanks again for reporting!
