### ISSUE TITLE
Expose all or most config options to the CLI

### ISSUE THREAD

**Issue by marcusedwardhaslam** [sgb-io/fta#50]
> In some instances test or spec files might not be pertinent to the user's output. It would be nice to have the ability to ignore certain files. e.g. `./fta ./src --ignore "*.test.*.js"`

This is achievable with `fta.json` configuration.. it'd be nice to have the same flags in the CLI

**Comment by sgb-io** [comment]
It should be noted that some CLI options are not config options.

This excersize should be adding each config option as CLI arguments. There would need to be a decision about which one wins when both are provided: my initial reaction is that CLI arguments should override options specified in `fta.json`

**Comment by sgb-io** [comment]
https://github.com/sgb-io/fta/pull/62 exposes 4 more options as CLI arguments, but I'm considering support for `extensions`, `exclude_filenames`, `exclude_directories` out of scope, as accepting string array values is a lot more complex.

These particular args could potentially be exposed as a single glob pattern (therefore a single string value) but this is not currently compatible with the config implementation where we have some default values and let the user extend those.

I'd be open to some explicit new options that are glob patterns and override the aforementioned config behaviour - obviously, this is a bit more involved.

**Comment by sgb-io** [comment]
See follow up issue: https://github.com/sgb-io/fta/issues/63
