### ISSUE TITLE
Incorrect halstead formulas

### ISSUE THREAD

**Issue by ugniusramanauskas** [sgb-io/fta#97]
Your documentation (as well as other Halstead documentations) clearly states:

Measure Name | Description
-- | --
Program Length (N) | The total count of operators and operands.
Program Vocabulary (n) | The total count of unique operators and operands.

However, your code does the opposite -- i.e. adds unique values in `program_length`, and totals in `vocabulary_size`:
```
        let program_length = uniq_operators + uniq_operands;
        let vocabulary_size = total_operators + total_operands;
```

As a result, all the other derivative measures - Volume, Difficulty, Effort, etc. - are also incorrectly calculated. 

p.s. Let me know if I can help with correcting this.

**Comment by sgb-io** [comment]
This fix is now available in v2.0.0. Thanks!

**Comment by ugniusramanauskas** [comment]
@sgb-io -- thanks so much for fixing it so quickly! I can see the new "v2.0.0" tag, but no release yet. When do you plan on marking it as an official release? Just curious.

**Comment by sgb-io** [comment]
@ugniusramanauskas the Rust crate and npm package have been available for a few days, but I forgot to publish the Github release. I have now done so. Thanks!
